sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: uTkqMUb1A5HgPRqi6wRjHk/5DQigkYXYw9fSW4Bol1ow4W+ey9BA9Mq+sDy118j80vKAybRmQ9WTSJZZRb/Gdlh6u8e7jhl6GtnIgGcvW2jj7UCjZdXbpiVwRBRieB67rCPTMNcYCBLWA4RQMCZ2UqnANyRclB/ycrzsXzsstZPIPI1+NZiwkUPerct+75l4PeRjMo3GQ6maECsI/GgCxDbhW3LggUPDPqiboYtwwkBcsTBILXUpoVEZcQwKPSv9L2R5S6vvK9dWUmqiwiRCed4WqJ6u2SCEstdTKZrNEOSnObeog/wvKmzpNmMrXbgjHuu8Xpj7dCfoIVab2CMGL1/LnPXFuchlLYq5sQThONkgX94rH0+H+oYBQemtJ9N4fbaUdejt+Jp47DaIPU+eO03mQRixdVaPIwIQN6LwsaF6pIKwMy3/xw+fG5JdpmHankPdV3H4ewFhI8xHiOkazJELNanTHM9qOmXFICszVltHTYMfDE954uRWycGnjm/U96gVLDEFdkxkYdH2zFj/Cr2fHCoUjOKaGlDr/UFTy9sxL1ysNx5B8+DyGhEIi5l7/tN3twPjOxufAnBc3uRsH9Jy0HpUjJgn5gFVokRyW8ifYTAcluL9FQPAjl+oHWRbB06IJefnRILomm0nv7lxpSjodwYWJSMvxyBdvuq5vZQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Sparrows--The-Story-of-an-Unprotected-Girl_4345
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy